branches:
  only:
    - master

matrix:
  fast_finish: true
  include:
  - language: go
    go: 1.9
    script: ci/go.sh
  - language: node_js
    node_js: 9
    script: ci/js.sh
  - language: python
    python: 2.7
    script: ci/python.sh
  - language: python
    python: 3.6
    script: ci/python.sh
  - language: ruby
    rvm: 2.4.2
    script: ci/ruby.sh
  - language: ruby
    rvm: 2.2.2
    script: ci/ruby.sh
  # TODO: support stable Rust
  - language: rust
    rust: nightly
    script: ci/rust.sh

